# Generated by Django 5.2.17 on 2026-09-13 03:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('project_type', models.CharField(choices=[('website', 'Website'), ('web-development', 'Website Development'), ('competition', 'Competition'), ('other', 'Other')], default='other', max_length=30)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('tag1', models.CharField(blank=True, max_length=50)),
                ('tag2', models.CharField(blank=True, max_length=50)),
                ('tag3', models.CharField(blank=True, max_length=50)),
                ('tag4', models.CharField(blank=True, max_length=50)),
                ('detail_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
